variable "digital_ocean_token" {}
variable "ssh_key_file" {}
variable "domain_name" {}
variable "name" {}
variable "mysql_root_pwd" {}
variable "mysql_pwd" {}
variable "mysql_user" {}
variable "mysql_db" {}
variable "registry_user" {}
variable "registry_user_pwd" {}