version: '3'

services:
  app:
    image: gitea/gitea
    links:
      - db:mysql
    volumes:
      - app:/data
    environment:
      - VIRTUAL_PORT=3000
      - APP_NAME="Stigma Software Development"
      - RUN_MODE=prod
      - ROOT_URL=https://git.stigma.pw/
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_NAME=${MYSQL_USER}
      - DB_PASSWD=${MYSQL_PASSWORD}
      - INSTALL_LOCK=true
      - DISABLE_REGISTRATION=true
      - REQUIRE_SIGNIN_VIEW=true
      - SECRET_KEY=qpaEb65Avat4ANMa21vag
    networks:
      - backend
    deploy:
      placement:
        constraints: 
          - node.role == manager
  db:
    container_name: gitea-db
    restart: always
    image: mysql:5.6
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend
    deploy:
      placement:
        constraints: 
          - node.role == manager
networks:
  backend:

volumes:
  app:
  db:
