version: '3.2'

services:
 registry:
   image: registry:2
   environment:
     TCP_PORTS: '5000'
     VIRTUAL_HOST: '*:5000, https://*:5000'
     FORCE_SSL: 'false'
     REGISTRY_STORAGE_DELETE_ENABLED: 'true'
 registry-ui:
   image: konradkleine/docker-registry-frontend:v2
   environment:
     VIRTUAL_HOST: '*, https://*'
     ENV_DOCKER_REGISTRY_HOST: 'registry'
     ENV_DOCKER_REGISTRY_PORT: 5000

volumes:
  app: