version: '3.2'
services:
    jenkins:
        image: ptorrezao/jenkins
        volumes:
            - jenkins_home:/var/jenkins_home
    jenkins-slave:
        container_name: jenkins-dockerslave
        restart: always
        environment:
            - 'JENKINS_URL=http://jenkins:8080'
        image: ptorrezao/jenkins-slave
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock 
        depends_on:
            - jenkins
        deploy:
            replicas: 1

volumes:
  jenkins_home: