version: '3.2'

services:
  portainer:
    networks:
      - traefik_net
    deploy:
      labels:
        - traefik.docker.network=traefik_net
        - "traefik.frontend.rule=Host:portainer.${TARGET_DOMAIN}"
        - traefik.port=9000
        - traefik.protocol=http
        - traefik.backend=portainer
networks:
  traefik_net:
    external: true
