
version: '3'

services:
  app:
    networks:
      - traefik_net
    deploy:
      labels:
        - traefik.docker.network=traefik_net
        - "traefik.frontend.rule=Host:git.${TARGET_DOMAIN}"
        - traefik.port=3000
        - traefik.protocol=https
        - traefik.backend=gittea

networks:
  traefik_net:
    external: true
